### PR TITLE
fix: enforce .tsx file extension for dev command

### LINKED ISSUE #46: Better error message for `tsci dev file` command if it's not a tsx file
```bash
> bun cli/main.ts dev kom-senapati.custom-board-1/index.ts
Installing types for imported snippets...
Types installed successfully
Server running at http://localhost:3020
Checking initial type dependencies...
```

Image

### PR DESCRIPTION
**Pull request by k0msenapati**
Closes #46

### CODE REVIEW

File: cli/dev/register.ts [hunk 1]
```diff
@@ -38,6 +38,12 @@ export const registerDev = (program: Command) => {
 
       if (file) {
         absolutePath = path.resolve(file)
+        if (!absolutePath.endsWith(".tsx")) {
+          console.error(
+            "Error: Only .tsx file is supported for the dev command.",
```
Comment (seveibar) [inline cli/dev/register.ts]:
```suggestion
            "Error: Only .tsx files are supported",
```

**Review by seveibar — APPROVED** [review]

**Review by seveibar — APPROVED** [review]
