### PR TITLE
fix: Renaming files aren't picked up properly

### LINKED ISSUE #166: Renaming files aren't picked up properly
After a filesystem rename happens, RunFrame errors that the previous file couldn't be found. You can do a test where you have code like:

- notreferenced.tsx
- index.tsx

```tsx
import something from "./something2.tsx"
```

Now rename "notreferenced.tsx" to "something2.tsx". It will not be picked up (the circuit will refuse to render)

/bounty $20

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #166
Fixes #166 

## screenshots
Screenshot 2025-05-11 165257

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
very, very nice work /tip $15

File: cli/dev/DevServer.ts [hunk 1]
```diff
@@ -137,6 +146,56 @@ export class DevServer {
...
+      const fileContent = fs.readFileSync(newPath, "utf-8")
+      await this.fsKy.post("api/files/upsert", {
+        json: {
+          file_path: newRelativePath,
+          text_content: fileContent,
+          initiator: "filesystem_change",
+        },
+      })
+
+      console.log(`File renamed from ${oldRelativePath} to ${newRelativePath}`)
```
Comment (seveibar) [inline cli/dev/DevServer.ts]: idk if we need to log all this

Comment (seveibar) [reply cli/dev/DevServer.ts]: put it in a `debug` if it's useful for debugging sometimes

File: cli/dev/DevServer.ts [hunk 2]
```diff
@@ -14,6 +14,9 @@ import { globbySync } from "globby"
 import { ExportFormat, exportSnippet } from "lib/shared/export-snippet"
 import { getPackageFilePaths } from "./get-package-file-paths"
 import { addPackage } from "lib/shared/add-package"
+import Debug from "debug"
+
+const debug = Debug("devserver:fs")
```
Comment (seveibar) [inline cli/dev/DevServer.ts]:
```suggestion
const debug = Debug("tscircuit:devserver")
```

**Review by seveibar — CHANGES_REQUESTED** [review]
based on `test1` failing, i think you're normalizing in a non-standard way

with tscircuit, we always normalized file paths to NOT have a "/" prefix

File: tests/test6-file-rename.test.ts [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+
+test("test6 file renaming should be properly detected", async () => {
+  const fixture = await getCliTestFixture()
+
+  // Create initial files
+  const notreferencedPath = join(fixture.tmpDir, "notreferenced.tsx")
+  const indexPath = join(fixture.tmpDir, "index.tsx")
+  const something2Path = join(fixture.tmpDir, "something2.tsx")
+
+  console.log("Writing notreferenced.tsx...")
```
Comment (seveibar) [inline tests/test6-file-rename.test.ts]:
```suggestion
```

File: tests/test6-file-rename.test.ts [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+  await Bun.write(
+    notreferencedPath,
+    `
+    export const MyComponent = () => (
+      <div>Test Component</div>
+    )
+    `,
+  )
+
+  console.log("Writing index.tsx...")
```
Comment (seveibar) [inline tests/test6-file-rename.test.ts]:
```suggestion
```

**Review by seveibar — CHANGES_REQUESTED** [review]
logging everywhere

**Comment by Anshgrover23** [comment]
@seveibar logging is just for debugging i have removed and leave the logs wherever necessary.

File: cli/dev/DevServer.ts [hunk 5]
```diff
@@ -137,6 +149,56 @@ export class DevServer {
...
+  async handleFileRemovedFromFilesystem(absoluteFilePath: string) {
+    const relativeFilePath = path.relative(this.projectDir, absoluteFilePath)
+    try {
+      await this.fsKy.post("api/files/delete", {
+        json: {
+          file_path: relativeFilePath,
+          initiator: "filesystem_change",
+        },
+      })
+      console.log(`${relativeFilePath} deleted. Removed from file server.`)
```
Comment (seveibar) [inline cli/dev/DevServer.ts]:
```suggestion
```

File: cli/dev/DevServer.ts [hunk 6]
```diff
@@ -137,6 +149,56 @@ export class DevServer {
...
+    } catch (err: unknown) {
+      console.error(
+        `Failed to remove file from file server: ${relativeFilePath}`,
+        err,
+      )
+    }
```
Comment (seveibar) [inline cli/dev/DevServer.ts:200]: you're silencing this error, remove the try catch (same as the other ones)

File: cli/dev/DevServer.ts [hunk 7]
```diff
@@ -137,6 +149,56 @@ export class DevServer {
...
+          initiator: "filesystem_change",
+        },
+      })
+
+      debug(`File renamed from ${oldRelativePath} to ${newRelativePath}`)
+    } catch (err) {
+      console.error(
+        `Failed to handle file rename from ${oldRelativePath} to ${newRelativePath}:`,
+        err,
+      )
```
Comment (seveibar) [inline cli/dev/DevServer.ts]: you're silencing this error, remove the try catch

**Review by seveibar — COMMENTED** [review]
see comments

**Review by seveibar — APPROVED** [review]
