### PR TITLE
Fix: upload of binary files in tsci push

### LINKED ISSUE #1123: Issue running `tsci push`, internal server error
Image

It looks like maybe a file that shouldn't have been uploaded was attempted to be uploaded

### PR DESCRIPTION
**Pull request by MustafaMulla29**
/fixes https://github.com/tscircuit/cli/issues/1123
/closes https://github.com/tscircuit/cli/issues/1123

### CODE REVIEW

**Comment by MustafaMulla29** [comment]
@imrishabh18 tests are still failing here, even after your fix

**Comment by imrishabh18** [comment]
Interesting, try to change the zod version to this `"zod": "^3.25.67"` and run the workflow

**Review by seveibar — CHANGES_REQUESTED** [review]
we have to push binary files, this would break so many packages

**Comment by seveibar** [comment]
you have to change the request payload to update binary files

image

**Comment by MustafaMulla29** [comment]
Alright, I'll work on that

File: lib/shared/is-binary-file.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
+import * as path from "node:path"
```
Comment (seveibar) [inline lib/shared/is-binary-file.ts:1]: never create "utils" files- ALWAYS name files after the main function export e.g. `isBinaryFile` and move `hasBinaryContent` to a separate file

File: tests/cli/push/push13-gerber-files.test.ts [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+  // Create gerber files (common in PCB projects)
+  fs.mkdirSync(path.resolve(tmpDir, "gerbers"))
+  fs.writeFileSync(
+    path.resolve(tmpDir, "gerbers/board.gbr"),
+    Buffer.from([0x47, 0x34, 0x00, 0x00]), // Gerber-like content with null bytes
+  )
+  fs.writeFileSync(
+    path.resolve(tmpDir, "gerbers/board-F_Mask.gbr"),
+    Buffer.from([0x47, 0x34, 0x00, 0x00]),
+  )
```
Comment (seveibar) [inline tests/cli/push/push13-gerber-files.test.ts]: remove this. These aren't gerbers and the random bytes you're providing are nothing like a zip file

this test is _completely wrong_ because gerbers are text

File: tests/cli/push/push14-text-files-only.test.ts [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+  expect(stdout).toContain("⬆︎ snippet.tsx")
+  expect(stdout).toContain("⬆︎ README.md")
+  expect(stdout).toContain("⬆︎ tsconfig.json")
+
+  // Should NOT have any binary file uploads
+  expect(stdout).not.toContain("📦")
+
+  // Should successfully publish
+  expect(stdout).toContain("published!")
+  expect(stderr).toBe("")
```
Comment (seveibar) [inline tests/cli/push/push14-text-files-only.test.ts]: remove this, you're not testing anything new. This just increases our CI time

**Review by seveibar — CHANGES_REQUESTED** [review]
attempt to decode with UTF-8 to determine if it's binary

**Comment by MustafaMulla29** [comment]
@seveibar are the tests enough or do we need more tests for this?

**Review by seveibar — APPROVED** [review]
