### PR TITLE
Fix Either entrypoint or mainComponentPath must be provided

### LINKED ISSUE #174: Either entrypoint or mainComponentPath must be provided (no index file, could not infer entrypoint)
this is the first thing I get when cloning the cli and running bun start

Image

### PR DESCRIPTION
**Pull request by ArnavK-09**
fix https://github.com/tscircuit/cli/issues/174

### CODE REVIEW

File: lib/server/createHttpServer.ts [hunk 1]
```diff
@@ -10,9 +10,11 @@ import runFrameStandaloneBundleContent from "@tscircuit/runframe/standalone" wit
 // @ts-ignore
 import winterspecBundle from "@tscircuit/file-server/dist/bundle.js"
 import { getIndex } from "../site/getIndex"
-import kleur from "kleur"
 
-export const createHttpServer = async (port = 3020) => {
+export const createHttpServer = async (
+  port = 3020,
+  mainComponentPath?: string,
```
Comment (seveibar) [inline lib/server/createHttpServer.ts]: good time to convert to named arguments, `port` was obvious but the path is not obvious at all

**Review by seveibar — COMMENTED** [review]
should this be like `defaultMainComponentPath`? Can't the user change it from RunFrame (select other boards/files)?

**Review by seveibar — APPROVED** [review]
